apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hllp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hllp
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hllp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hllp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hllp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kskf-tenant/rhtap-demo-app/hacbs-test-project-hllp@sha256:d71d3f4c779a8143023e3d7e2f791e9c0c4397dcb9a287594a77ceb621dfac1d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
