apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hllp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kskf-tenant/rhtap-demo-app/hacbs-test-project-hllp@sha256:d71d3f4c779a8143023e3d7e2f791e9c0c4397dcb9a287594a77ceb621dfac1d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
